{-
   CRDOpenAPI

   No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

   OpenAPI Version: 3.0.1
   CRDOpenAPI API version: v1.15.2
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : Operator.Helm.OpenAPI.Lens
-}

{-# LANGUAGE KindSignatures #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE RecordWildCards #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-matches -fno-warn-unused-binds -fno-warn-unused-imports #-}

module Operator.Helm.OpenAPI.ModelLens where

import qualified Data.Aeson as A
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Data, Typeable)
import qualified Data.Map as Map
import qualified Data.Set as Set
import qualified Data.Time as TI

import Data.Text (Text)

import Prelude (($), (.),(<$>),(<*>),(=<<),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

import Operator.Helm.OpenAPI.Model
import Kubernetes.OpenAPI.Core


-- * V1HelmRelease

-- | 'v1HelmReleaseApiVersion' Lens
v1HelmReleaseApiVersionL :: Lens_' V1HelmRelease (Maybe Text)
v1HelmReleaseApiVersionL f V1HelmRelease{..} = (\v1HelmReleaseApiVersion -> V1HelmRelease { v1HelmReleaseApiVersion, ..} ) <$> f v1HelmReleaseApiVersion
{-# INLINE v1HelmReleaseApiVersionL #-}

-- | 'v1HelmReleaseKind' Lens
v1HelmReleaseKindL :: Lens_' V1HelmRelease (Maybe Text)
v1HelmReleaseKindL f V1HelmRelease{..} = (\v1HelmReleaseKind -> V1HelmRelease { v1HelmReleaseKind, ..} ) <$> f v1HelmReleaseKind
{-# INLINE v1HelmReleaseKindL #-}

-- | 'v1HelmReleaseMetadata' Lens
v1HelmReleaseMetadataL :: Lens_' V1HelmRelease (Maybe V1ObjectMeta)
v1HelmReleaseMetadataL f V1HelmRelease{..} = (\v1HelmReleaseMetadata -> V1HelmRelease { v1HelmReleaseMetadata, ..} ) <$> f v1HelmReleaseMetadata
{-# INLINE v1HelmReleaseMetadataL #-}

-- | 'v1HelmReleaseSpec' Lens
v1HelmReleaseSpecL :: Lens_' V1HelmRelease (Maybe V1HelmReleaseSpec)
v1HelmReleaseSpecL f V1HelmRelease{..} = (\v1HelmReleaseSpec -> V1HelmRelease { v1HelmReleaseSpec, ..} ) <$> f v1HelmReleaseSpec
{-# INLINE v1HelmReleaseSpecL #-}

-- | 'v1HelmReleaseStatus' Lens
v1HelmReleaseStatusL :: Lens_' V1HelmRelease (Maybe V1HelmReleaseStatus)
v1HelmReleaseStatusL f V1HelmRelease{..} = (\v1HelmReleaseStatus -> V1HelmRelease { v1HelmReleaseStatus, ..} ) <$> f v1HelmReleaseStatus
{-# INLINE v1HelmReleaseStatusL #-}



-- * V1HelmReleaseList

-- | 'v1HelmReleaseListApiVersion' Lens
v1HelmReleaseListApiVersionL :: Lens_' V1HelmReleaseList (Maybe Text)
v1HelmReleaseListApiVersionL f V1HelmReleaseList{..} = (\v1HelmReleaseListApiVersion -> V1HelmReleaseList { v1HelmReleaseListApiVersion, ..} ) <$> f v1HelmReleaseListApiVersion
{-# INLINE v1HelmReleaseListApiVersionL #-}

-- | 'v1HelmReleaseListItems' Lens
v1HelmReleaseListItemsL :: Lens_' V1HelmReleaseList ([V1HelmRelease])
v1HelmReleaseListItemsL f V1HelmReleaseList{..} = (\v1HelmReleaseListItems -> V1HelmReleaseList { v1HelmReleaseListItems, ..} ) <$> f v1HelmReleaseListItems
{-# INLINE v1HelmReleaseListItemsL #-}

-- | 'v1HelmReleaseListKind' Lens
v1HelmReleaseListKindL :: Lens_' V1HelmReleaseList (Maybe Text)
v1HelmReleaseListKindL f V1HelmReleaseList{..} = (\v1HelmReleaseListKind -> V1HelmReleaseList { v1HelmReleaseListKind, ..} ) <$> f v1HelmReleaseListKind
{-# INLINE v1HelmReleaseListKindL #-}

-- | 'v1HelmReleaseListMetadata' Lens
v1HelmReleaseListMetadataL :: Lens_' V1HelmReleaseList (Maybe V1HelmReleaseListMetadata)
v1HelmReleaseListMetadataL f V1HelmReleaseList{..} = (\v1HelmReleaseListMetadata -> V1HelmReleaseList { v1HelmReleaseListMetadata, ..} ) <$> f v1HelmReleaseListMetadata
{-# INLINE v1HelmReleaseListMetadataL #-}



-- * V1HelmReleaseListMetadata

-- | 'v1HelmReleaseListMetadataContinue' Lens
v1HelmReleaseListMetadataContinueL :: Lens_' V1HelmReleaseListMetadata (Maybe Text)
v1HelmReleaseListMetadataContinueL f V1HelmReleaseListMetadata{..} = (\v1HelmReleaseListMetadataContinue -> V1HelmReleaseListMetadata { v1HelmReleaseListMetadataContinue, ..} ) <$> f v1HelmReleaseListMetadataContinue
{-# INLINE v1HelmReleaseListMetadataContinueL #-}

-- | 'v1HelmReleaseListMetadataRemainingItemCount' Lens
v1HelmReleaseListMetadataRemainingItemCountL :: Lens_' V1HelmReleaseListMetadata (Maybe Integer)
v1HelmReleaseListMetadataRemainingItemCountL f V1HelmReleaseListMetadata{..} = (\v1HelmReleaseListMetadataRemainingItemCount -> V1HelmReleaseListMetadata { v1HelmReleaseListMetadataRemainingItemCount, ..} ) <$> f v1HelmReleaseListMetadataRemainingItemCount
{-# INLINE v1HelmReleaseListMetadataRemainingItemCountL #-}

-- | 'v1HelmReleaseListMetadataResourceVersion' Lens
v1HelmReleaseListMetadataResourceVersionL :: Lens_' V1HelmReleaseListMetadata (Maybe Text)
v1HelmReleaseListMetadataResourceVersionL f V1HelmReleaseListMetadata{..} = (\v1HelmReleaseListMetadataResourceVersion -> V1HelmReleaseListMetadata { v1HelmReleaseListMetadataResourceVersion, ..} ) <$> f v1HelmReleaseListMetadataResourceVersion
{-# INLINE v1HelmReleaseListMetadataResourceVersionL #-}

-- | 'v1HelmReleaseListMetadataSelfLink' Lens
v1HelmReleaseListMetadataSelfLinkL :: Lens_' V1HelmReleaseListMetadata (Maybe Text)
v1HelmReleaseListMetadataSelfLinkL f V1HelmReleaseListMetadata{..} = (\v1HelmReleaseListMetadataSelfLink -> V1HelmReleaseListMetadata { v1HelmReleaseListMetadataSelfLink, ..} ) <$> f v1HelmReleaseListMetadataSelfLink
{-# INLINE v1HelmReleaseListMetadataSelfLinkL #-}



-- * V1HelmReleaseSpec

-- | 'v1HelmReleaseSpecChart' Lens
v1HelmReleaseSpecChartL :: Lens_' V1HelmReleaseSpec (V1HelmReleaseSpecChart)
v1HelmReleaseSpecChartL f V1HelmReleaseSpec{..} = (\v1HelmReleaseSpecChart -> V1HelmReleaseSpec { v1HelmReleaseSpecChart, ..} ) <$> f v1HelmReleaseSpecChart
{-# INLINE v1HelmReleaseSpecChartL #-}

-- | 'v1HelmReleaseSpecDisableOpenApiValidation' Lens
v1HelmReleaseSpecDisableOpenApiValidationL :: Lens_' V1HelmReleaseSpec (Maybe Bool)
v1HelmReleaseSpecDisableOpenApiValidationL f V1HelmReleaseSpec{..} = (\v1HelmReleaseSpecDisableOpenApiValidation -> V1HelmReleaseSpec { v1HelmReleaseSpecDisableOpenApiValidation, ..} ) <$> f v1HelmReleaseSpecDisableOpenApiValidation
{-# INLINE v1HelmReleaseSpecDisableOpenApiValidationL #-}

-- | 'v1HelmReleaseSpecForceUpgrade' Lens
v1HelmReleaseSpecForceUpgradeL :: Lens_' V1HelmReleaseSpec (Maybe Bool)
v1HelmReleaseSpecForceUpgradeL f V1HelmReleaseSpec{..} = (\v1HelmReleaseSpecForceUpgrade -> V1HelmReleaseSpec { v1HelmReleaseSpecForceUpgrade, ..} ) <$> f v1HelmReleaseSpecForceUpgrade
{-# INLINE v1HelmReleaseSpecForceUpgradeL #-}

-- | 'v1HelmReleaseSpecHelmVersion' Lens
v1HelmReleaseSpecHelmVersionL :: Lens_' V1HelmReleaseSpec (Maybe E'HelmVersion)
v1HelmReleaseSpecHelmVersionL f V1HelmReleaseSpec{..} = (\v1HelmReleaseSpecHelmVersion -> V1HelmReleaseSpec { v1HelmReleaseSpecHelmVersion, ..} ) <$> f v1HelmReleaseSpecHelmVersion
{-# INLINE v1HelmReleaseSpecHelmVersionL #-}

-- | 'v1HelmReleaseSpecMaxHistory' Lens
v1HelmReleaseSpecMaxHistoryL :: Lens_' V1HelmReleaseSpec (Maybe Int)
v1HelmReleaseSpecMaxHistoryL f V1HelmReleaseSpec{..} = (\v1HelmReleaseSpecMaxHistory -> V1HelmReleaseSpec { v1HelmReleaseSpecMaxHistory, ..} ) <$> f v1HelmReleaseSpecMaxHistory
{-# INLINE v1HelmReleaseSpecMaxHistoryL #-}

-- | 'v1HelmReleaseSpecReleaseName' Lens
v1HelmReleaseSpecReleaseNameL :: Lens_' V1HelmReleaseSpec (Maybe Text)
v1HelmReleaseSpecReleaseNameL f V1HelmReleaseSpec{..} = (\v1HelmReleaseSpecReleaseName -> V1HelmReleaseSpec { v1HelmReleaseSpecReleaseName, ..} ) <$> f v1HelmReleaseSpecReleaseName
{-# INLINE v1HelmReleaseSpecReleaseNameL #-}

-- | 'v1HelmReleaseSpecResetValues' Lens
v1HelmReleaseSpecResetValuesL :: Lens_' V1HelmReleaseSpec (Maybe Bool)
v1HelmReleaseSpecResetValuesL f V1HelmReleaseSpec{..} = (\v1HelmReleaseSpecResetValues -> V1HelmReleaseSpec { v1HelmReleaseSpecResetValues, ..} ) <$> f v1HelmReleaseSpecResetValues
{-# INLINE v1HelmReleaseSpecResetValuesL #-}

-- | 'v1HelmReleaseSpecRollback' Lens
v1HelmReleaseSpecRollbackL :: Lens_' V1HelmReleaseSpec (Maybe V1HelmReleaseSpecRollback)
v1HelmReleaseSpecRollbackL f V1HelmReleaseSpec{..} = (\v1HelmReleaseSpecRollback -> V1HelmReleaseSpec { v1HelmReleaseSpecRollback, ..} ) <$> f v1HelmReleaseSpecRollback
{-# INLINE v1HelmReleaseSpecRollbackL #-}

-- | 'v1HelmReleaseSpecSkipCrDs' Lens
v1HelmReleaseSpecSkipCrDsL :: Lens_' V1HelmReleaseSpec (Maybe Bool)
v1HelmReleaseSpecSkipCrDsL f V1HelmReleaseSpec{..} = (\v1HelmReleaseSpecSkipCrDs -> V1HelmReleaseSpec { v1HelmReleaseSpecSkipCrDs, ..} ) <$> f v1HelmReleaseSpecSkipCrDs
{-# INLINE v1HelmReleaseSpecSkipCrDsL #-}

-- | 'v1HelmReleaseSpecTargetNamespace' Lens
v1HelmReleaseSpecTargetNamespaceL :: Lens_' V1HelmReleaseSpec (Maybe Text)
v1HelmReleaseSpecTargetNamespaceL f V1HelmReleaseSpec{..} = (\v1HelmReleaseSpecTargetNamespace -> V1HelmReleaseSpec { v1HelmReleaseSpecTargetNamespace, ..} ) <$> f v1HelmReleaseSpecTargetNamespace
{-# INLINE v1HelmReleaseSpecTargetNamespaceL #-}

-- | 'v1HelmReleaseSpecTest' Lens
v1HelmReleaseSpecTestL :: Lens_' V1HelmReleaseSpec (Maybe V1HelmReleaseSpecTest)
v1HelmReleaseSpecTestL f V1HelmReleaseSpec{..} = (\v1HelmReleaseSpecTest -> V1HelmReleaseSpec { v1HelmReleaseSpecTest, ..} ) <$> f v1HelmReleaseSpecTest
{-# INLINE v1HelmReleaseSpecTestL #-}

-- | 'v1HelmReleaseSpecTimeout' Lens
v1HelmReleaseSpecTimeoutL :: Lens_' V1HelmReleaseSpec (Maybe Integer)
v1HelmReleaseSpecTimeoutL f V1HelmReleaseSpec{..} = (\v1HelmReleaseSpecTimeout -> V1HelmReleaseSpec { v1HelmReleaseSpecTimeout, ..} ) <$> f v1HelmReleaseSpecTimeout
{-# INLINE v1HelmReleaseSpecTimeoutL #-}

-- | 'v1HelmReleaseSpecValueFileSecrets' Lens
v1HelmReleaseSpecValueFileSecretsL :: Lens_' V1HelmReleaseSpec (Maybe [V1HelmReleaseSpecValueFileSecrets])
v1HelmReleaseSpecValueFileSecretsL f V1HelmReleaseSpec{..} = (\v1HelmReleaseSpecValueFileSecrets -> V1HelmReleaseSpec { v1HelmReleaseSpecValueFileSecrets, ..} ) <$> f v1HelmReleaseSpecValueFileSecrets
{-# INLINE v1HelmReleaseSpecValueFileSecretsL #-}

-- | 'v1HelmReleaseSpecValues' Lens
v1HelmReleaseSpecValuesL :: Lens_' V1HelmReleaseSpec (Maybe A.Value)
v1HelmReleaseSpecValuesL f V1HelmReleaseSpec{..} = (\v1HelmReleaseSpecValues -> V1HelmReleaseSpec { v1HelmReleaseSpecValues, ..} ) <$> f v1HelmReleaseSpecValues
{-# INLINE v1HelmReleaseSpecValuesL #-}

-- | 'v1HelmReleaseSpecValuesFrom' Lens
v1HelmReleaseSpecValuesFromL :: Lens_' V1HelmReleaseSpec (Maybe [V1HelmReleaseSpecValuesFrom])
v1HelmReleaseSpecValuesFromL f V1HelmReleaseSpec{..} = (\v1HelmReleaseSpecValuesFrom -> V1HelmReleaseSpec { v1HelmReleaseSpecValuesFrom, ..} ) <$> f v1HelmReleaseSpecValuesFrom
{-# INLINE v1HelmReleaseSpecValuesFromL #-}

-- | 'v1HelmReleaseSpecWait' Lens
v1HelmReleaseSpecWaitL :: Lens_' V1HelmReleaseSpec (Maybe Bool)
v1HelmReleaseSpecWaitL f V1HelmReleaseSpec{..} = (\v1HelmReleaseSpecWait -> V1HelmReleaseSpec { v1HelmReleaseSpecWait, ..} ) <$> f v1HelmReleaseSpecWait
{-# INLINE v1HelmReleaseSpecWaitL #-}



-- * V1HelmReleaseSpecChart

-- | 'v1HelmReleaseSpecChartChartPullSecret' Lens
v1HelmReleaseSpecChartChartPullSecretL :: Lens_' V1HelmReleaseSpecChart (Maybe V1HelmReleaseSpecChartChartPullSecret)
v1HelmReleaseSpecChartChartPullSecretL f V1HelmReleaseSpecChart{..} = (\v1HelmReleaseSpecChartChartPullSecret -> V1HelmReleaseSpecChart { v1HelmReleaseSpecChartChartPullSecret, ..} ) <$> f v1HelmReleaseSpecChartChartPullSecret
{-# INLINE v1HelmReleaseSpecChartChartPullSecretL #-}

-- | 'v1HelmReleaseSpecChartGit' Lens
v1HelmReleaseSpecChartGitL :: Lens_' V1HelmReleaseSpecChart (Maybe Text)
v1HelmReleaseSpecChartGitL f V1HelmReleaseSpecChart{..} = (\v1HelmReleaseSpecChartGit -> V1HelmReleaseSpecChart { v1HelmReleaseSpecChartGit, ..} ) <$> f v1HelmReleaseSpecChartGit
{-# INLINE v1HelmReleaseSpecChartGitL #-}

-- | 'v1HelmReleaseSpecChartName' Lens
v1HelmReleaseSpecChartNameL :: Lens_' V1HelmReleaseSpecChart (Maybe Text)
v1HelmReleaseSpecChartNameL f V1HelmReleaseSpecChart{..} = (\v1HelmReleaseSpecChartName -> V1HelmReleaseSpecChart { v1HelmReleaseSpecChartName, ..} ) <$> f v1HelmReleaseSpecChartName
{-# INLINE v1HelmReleaseSpecChartNameL #-}

-- | 'v1HelmReleaseSpecChartPath' Lens
v1HelmReleaseSpecChartPathL :: Lens_' V1HelmReleaseSpecChart (Maybe Text)
v1HelmReleaseSpecChartPathL f V1HelmReleaseSpecChart{..} = (\v1HelmReleaseSpecChartPath -> V1HelmReleaseSpecChart { v1HelmReleaseSpecChartPath, ..} ) <$> f v1HelmReleaseSpecChartPath
{-# INLINE v1HelmReleaseSpecChartPathL #-}

-- | 'v1HelmReleaseSpecChartRef' Lens
v1HelmReleaseSpecChartRefL :: Lens_' V1HelmReleaseSpecChart (Maybe Text)
v1HelmReleaseSpecChartRefL f V1HelmReleaseSpecChart{..} = (\v1HelmReleaseSpecChartRef -> V1HelmReleaseSpecChart { v1HelmReleaseSpecChartRef, ..} ) <$> f v1HelmReleaseSpecChartRef
{-# INLINE v1HelmReleaseSpecChartRefL #-}

-- | 'v1HelmReleaseSpecChartRepository' Lens
v1HelmReleaseSpecChartRepositoryL :: Lens_' V1HelmReleaseSpecChart (Maybe Text)
v1HelmReleaseSpecChartRepositoryL f V1HelmReleaseSpecChart{..} = (\v1HelmReleaseSpecChartRepository -> V1HelmReleaseSpecChart { v1HelmReleaseSpecChartRepository, ..} ) <$> f v1HelmReleaseSpecChartRepository
{-# INLINE v1HelmReleaseSpecChartRepositoryL #-}

-- | 'v1HelmReleaseSpecChartSecretRef' Lens
v1HelmReleaseSpecChartSecretRefL :: Lens_' V1HelmReleaseSpecChart (Maybe V1HelmReleaseSpecChartSecretRef)
v1HelmReleaseSpecChartSecretRefL f V1HelmReleaseSpecChart{..} = (\v1HelmReleaseSpecChartSecretRef -> V1HelmReleaseSpecChart { v1HelmReleaseSpecChartSecretRef, ..} ) <$> f v1HelmReleaseSpecChartSecretRef
{-# INLINE v1HelmReleaseSpecChartSecretRefL #-}

-- | 'v1HelmReleaseSpecChartSkipDepUpdate' Lens
v1HelmReleaseSpecChartSkipDepUpdateL :: Lens_' V1HelmReleaseSpecChart (Maybe Bool)
v1HelmReleaseSpecChartSkipDepUpdateL f V1HelmReleaseSpecChart{..} = (\v1HelmReleaseSpecChartSkipDepUpdate -> V1HelmReleaseSpecChart { v1HelmReleaseSpecChartSkipDepUpdate, ..} ) <$> f v1HelmReleaseSpecChartSkipDepUpdate
{-# INLINE v1HelmReleaseSpecChartSkipDepUpdateL #-}

-- | 'v1HelmReleaseSpecChartVersion' Lens
v1HelmReleaseSpecChartVersionL :: Lens_' V1HelmReleaseSpecChart (Maybe Text)
v1HelmReleaseSpecChartVersionL f V1HelmReleaseSpecChart{..} = (\v1HelmReleaseSpecChartVersion -> V1HelmReleaseSpecChart { v1HelmReleaseSpecChartVersion, ..} ) <$> f v1HelmReleaseSpecChartVersion
{-# INLINE v1HelmReleaseSpecChartVersionL #-}



-- * V1HelmReleaseSpecChartChartPullSecret

-- | 'v1HelmReleaseSpecChartChartPullSecretName' Lens
v1HelmReleaseSpecChartChartPullSecretNameL :: Lens_' V1HelmReleaseSpecChartChartPullSecret (Text)
v1HelmReleaseSpecChartChartPullSecretNameL f V1HelmReleaseSpecChartChartPullSecret{..} = (\v1HelmReleaseSpecChartChartPullSecretName -> V1HelmReleaseSpecChartChartPullSecret { v1HelmReleaseSpecChartChartPullSecretName, ..} ) <$> f v1HelmReleaseSpecChartChartPullSecretName
{-# INLINE v1HelmReleaseSpecChartChartPullSecretNameL #-}



-- * V1HelmReleaseSpecChartFileRef

-- | 'v1HelmReleaseSpecChartFileRefOptional' Lens
v1HelmReleaseSpecChartFileRefOptionalL :: Lens_' V1HelmReleaseSpecChartFileRef (Maybe Bool)
v1HelmReleaseSpecChartFileRefOptionalL f V1HelmReleaseSpecChartFileRef{..} = (\v1HelmReleaseSpecChartFileRefOptional -> V1HelmReleaseSpecChartFileRef { v1HelmReleaseSpecChartFileRefOptional, ..} ) <$> f v1HelmReleaseSpecChartFileRefOptional
{-# INLINE v1HelmReleaseSpecChartFileRefOptionalL #-}

-- | 'v1HelmReleaseSpecChartFileRefPath' Lens
v1HelmReleaseSpecChartFileRefPathL :: Lens_' V1HelmReleaseSpecChartFileRef (Text)
v1HelmReleaseSpecChartFileRefPathL f V1HelmReleaseSpecChartFileRef{..} = (\v1HelmReleaseSpecChartFileRefPath -> V1HelmReleaseSpecChartFileRef { v1HelmReleaseSpecChartFileRefPath, ..} ) <$> f v1HelmReleaseSpecChartFileRefPath
{-# INLINE v1HelmReleaseSpecChartFileRefPathL #-}



-- * V1HelmReleaseSpecChartSecretRef

-- | 'v1HelmReleaseSpecChartSecretRefName' Lens
v1HelmReleaseSpecChartSecretRefNameL :: Lens_' V1HelmReleaseSpecChartSecretRef (Text)
v1HelmReleaseSpecChartSecretRefNameL f V1HelmReleaseSpecChartSecretRef{..} = (\v1HelmReleaseSpecChartSecretRefName -> V1HelmReleaseSpecChartSecretRef { v1HelmReleaseSpecChartSecretRefName, ..} ) <$> f v1HelmReleaseSpecChartSecretRefName
{-# INLINE v1HelmReleaseSpecChartSecretRefNameL #-}

-- | 'v1HelmReleaseSpecChartSecretRefNamespace' Lens
v1HelmReleaseSpecChartSecretRefNamespaceL :: Lens_' V1HelmReleaseSpecChartSecretRef (Maybe Text)
v1HelmReleaseSpecChartSecretRefNamespaceL f V1HelmReleaseSpecChartSecretRef{..} = (\v1HelmReleaseSpecChartSecretRefNamespace -> V1HelmReleaseSpecChartSecretRef { v1HelmReleaseSpecChartSecretRefNamespace, ..} ) <$> f v1HelmReleaseSpecChartSecretRefNamespace
{-# INLINE v1HelmReleaseSpecChartSecretRefNamespaceL #-}



-- * V1HelmReleaseSpecConfigMapKeyRef

-- | 'v1HelmReleaseSpecConfigMapKeyRefKey' Lens
v1HelmReleaseSpecConfigMapKeyRefKeyL :: Lens_' V1HelmReleaseSpecConfigMapKeyRef (Maybe Text)
v1HelmReleaseSpecConfigMapKeyRefKeyL f V1HelmReleaseSpecConfigMapKeyRef{..} = (\v1HelmReleaseSpecConfigMapKeyRefKey -> V1HelmReleaseSpecConfigMapKeyRef { v1HelmReleaseSpecConfigMapKeyRefKey, ..} ) <$> f v1HelmReleaseSpecConfigMapKeyRefKey
{-# INLINE v1HelmReleaseSpecConfigMapKeyRefKeyL #-}

-- | 'v1HelmReleaseSpecConfigMapKeyRefName' Lens
v1HelmReleaseSpecConfigMapKeyRefNameL :: Lens_' V1HelmReleaseSpecConfigMapKeyRef (Text)
v1HelmReleaseSpecConfigMapKeyRefNameL f V1HelmReleaseSpecConfigMapKeyRef{..} = (\v1HelmReleaseSpecConfigMapKeyRefName -> V1HelmReleaseSpecConfigMapKeyRef { v1HelmReleaseSpecConfigMapKeyRefName, ..} ) <$> f v1HelmReleaseSpecConfigMapKeyRefName
{-# INLINE v1HelmReleaseSpecConfigMapKeyRefNameL #-}

-- | 'v1HelmReleaseSpecConfigMapKeyRefNamespace' Lens
v1HelmReleaseSpecConfigMapKeyRefNamespaceL :: Lens_' V1HelmReleaseSpecConfigMapKeyRef (Maybe Text)
v1HelmReleaseSpecConfigMapKeyRefNamespaceL f V1HelmReleaseSpecConfigMapKeyRef{..} = (\v1HelmReleaseSpecConfigMapKeyRefNamespace -> V1HelmReleaseSpecConfigMapKeyRef { v1HelmReleaseSpecConfigMapKeyRefNamespace, ..} ) <$> f v1HelmReleaseSpecConfigMapKeyRefNamespace
{-# INLINE v1HelmReleaseSpecConfigMapKeyRefNamespaceL #-}

-- | 'v1HelmReleaseSpecConfigMapKeyRefOptional' Lens
v1HelmReleaseSpecConfigMapKeyRefOptionalL :: Lens_' V1HelmReleaseSpecConfigMapKeyRef (Maybe Bool)
v1HelmReleaseSpecConfigMapKeyRefOptionalL f V1HelmReleaseSpecConfigMapKeyRef{..} = (\v1HelmReleaseSpecConfigMapKeyRefOptional -> V1HelmReleaseSpecConfigMapKeyRef { v1HelmReleaseSpecConfigMapKeyRefOptional, ..} ) <$> f v1HelmReleaseSpecConfigMapKeyRefOptional
{-# INLINE v1HelmReleaseSpecConfigMapKeyRefOptionalL #-}



-- * V1HelmReleaseSpecExternalSourceRef

-- | 'v1HelmReleaseSpecExternalSourceRefOptional' Lens
v1HelmReleaseSpecExternalSourceRefOptionalL :: Lens_' V1HelmReleaseSpecExternalSourceRef (Maybe Bool)
v1HelmReleaseSpecExternalSourceRefOptionalL f V1HelmReleaseSpecExternalSourceRef{..} = (\v1HelmReleaseSpecExternalSourceRefOptional -> V1HelmReleaseSpecExternalSourceRef { v1HelmReleaseSpecExternalSourceRefOptional, ..} ) <$> f v1HelmReleaseSpecExternalSourceRefOptional
{-# INLINE v1HelmReleaseSpecExternalSourceRefOptionalL #-}

-- | 'v1HelmReleaseSpecExternalSourceRefUrl' Lens
v1HelmReleaseSpecExternalSourceRefUrlL :: Lens_' V1HelmReleaseSpecExternalSourceRef (Text)
v1HelmReleaseSpecExternalSourceRefUrlL f V1HelmReleaseSpecExternalSourceRef{..} = (\v1HelmReleaseSpecExternalSourceRefUrl -> V1HelmReleaseSpecExternalSourceRef { v1HelmReleaseSpecExternalSourceRefUrl, ..} ) <$> f v1HelmReleaseSpecExternalSourceRefUrl
{-# INLINE v1HelmReleaseSpecExternalSourceRefUrlL #-}



-- * V1HelmReleaseSpecRollback

-- | 'v1HelmReleaseSpecRollbackDisableHooks' Lens
v1HelmReleaseSpecRollbackDisableHooksL :: Lens_' V1HelmReleaseSpecRollback (Maybe Bool)
v1HelmReleaseSpecRollbackDisableHooksL f V1HelmReleaseSpecRollback{..} = (\v1HelmReleaseSpecRollbackDisableHooks -> V1HelmReleaseSpecRollback { v1HelmReleaseSpecRollbackDisableHooks, ..} ) <$> f v1HelmReleaseSpecRollbackDisableHooks
{-# INLINE v1HelmReleaseSpecRollbackDisableHooksL #-}

-- | 'v1HelmReleaseSpecRollbackEnable' Lens
v1HelmReleaseSpecRollbackEnableL :: Lens_' V1HelmReleaseSpecRollback (Maybe Bool)
v1HelmReleaseSpecRollbackEnableL f V1HelmReleaseSpecRollback{..} = (\v1HelmReleaseSpecRollbackEnable -> V1HelmReleaseSpecRollback { v1HelmReleaseSpecRollbackEnable, ..} ) <$> f v1HelmReleaseSpecRollbackEnable
{-# INLINE v1HelmReleaseSpecRollbackEnableL #-}

-- | 'v1HelmReleaseSpecRollbackForce' Lens
v1HelmReleaseSpecRollbackForceL :: Lens_' V1HelmReleaseSpecRollback (Maybe Bool)
v1HelmReleaseSpecRollbackForceL f V1HelmReleaseSpecRollback{..} = (\v1HelmReleaseSpecRollbackForce -> V1HelmReleaseSpecRollback { v1HelmReleaseSpecRollbackForce, ..} ) <$> f v1HelmReleaseSpecRollbackForce
{-# INLINE v1HelmReleaseSpecRollbackForceL #-}

-- | 'v1HelmReleaseSpecRollbackMaxRetries' Lens
v1HelmReleaseSpecRollbackMaxRetriesL :: Lens_' V1HelmReleaseSpecRollback (Maybe Integer)
v1HelmReleaseSpecRollbackMaxRetriesL f V1HelmReleaseSpecRollback{..} = (\v1HelmReleaseSpecRollbackMaxRetries -> V1HelmReleaseSpecRollback { v1HelmReleaseSpecRollbackMaxRetries, ..} ) <$> f v1HelmReleaseSpecRollbackMaxRetries
{-# INLINE v1HelmReleaseSpecRollbackMaxRetriesL #-}

-- | 'v1HelmReleaseSpecRollbackRecreate' Lens
v1HelmReleaseSpecRollbackRecreateL :: Lens_' V1HelmReleaseSpecRollback (Maybe Bool)
v1HelmReleaseSpecRollbackRecreateL f V1HelmReleaseSpecRollback{..} = (\v1HelmReleaseSpecRollbackRecreate -> V1HelmReleaseSpecRollback { v1HelmReleaseSpecRollbackRecreate, ..} ) <$> f v1HelmReleaseSpecRollbackRecreate
{-# INLINE v1HelmReleaseSpecRollbackRecreateL #-}

-- | 'v1HelmReleaseSpecRollbackRetry' Lens
v1HelmReleaseSpecRollbackRetryL :: Lens_' V1HelmReleaseSpecRollback (Maybe Bool)
v1HelmReleaseSpecRollbackRetryL f V1HelmReleaseSpecRollback{..} = (\v1HelmReleaseSpecRollbackRetry -> V1HelmReleaseSpecRollback { v1HelmReleaseSpecRollbackRetry, ..} ) <$> f v1HelmReleaseSpecRollbackRetry
{-# INLINE v1HelmReleaseSpecRollbackRetryL #-}

-- | 'v1HelmReleaseSpecRollbackTimeout' Lens
v1HelmReleaseSpecRollbackTimeoutL :: Lens_' V1HelmReleaseSpecRollback (Maybe Integer)
v1HelmReleaseSpecRollbackTimeoutL f V1HelmReleaseSpecRollback{..} = (\v1HelmReleaseSpecRollbackTimeout -> V1HelmReleaseSpecRollback { v1HelmReleaseSpecRollbackTimeout, ..} ) <$> f v1HelmReleaseSpecRollbackTimeout
{-# INLINE v1HelmReleaseSpecRollbackTimeoutL #-}

-- | 'v1HelmReleaseSpecRollbackWait' Lens
v1HelmReleaseSpecRollbackWaitL :: Lens_' V1HelmReleaseSpecRollback (Maybe Bool)
v1HelmReleaseSpecRollbackWaitL f V1HelmReleaseSpecRollback{..} = (\v1HelmReleaseSpecRollbackWait -> V1HelmReleaseSpecRollback { v1HelmReleaseSpecRollbackWait, ..} ) <$> f v1HelmReleaseSpecRollbackWait
{-# INLINE v1HelmReleaseSpecRollbackWaitL #-}



-- * V1HelmReleaseSpecSecretKeyRef

-- | 'v1HelmReleaseSpecSecretKeyRefKey' Lens
v1HelmReleaseSpecSecretKeyRefKeyL :: Lens_' V1HelmReleaseSpecSecretKeyRef (Maybe Text)
v1HelmReleaseSpecSecretKeyRefKeyL f V1HelmReleaseSpecSecretKeyRef{..} = (\v1HelmReleaseSpecSecretKeyRefKey -> V1HelmReleaseSpecSecretKeyRef { v1HelmReleaseSpecSecretKeyRefKey, ..} ) <$> f v1HelmReleaseSpecSecretKeyRefKey
{-# INLINE v1HelmReleaseSpecSecretKeyRefKeyL #-}

-- | 'v1HelmReleaseSpecSecretKeyRefName' Lens
v1HelmReleaseSpecSecretKeyRefNameL :: Lens_' V1HelmReleaseSpecSecretKeyRef (Text)
v1HelmReleaseSpecSecretKeyRefNameL f V1HelmReleaseSpecSecretKeyRef{..} = (\v1HelmReleaseSpecSecretKeyRefName -> V1HelmReleaseSpecSecretKeyRef { v1HelmReleaseSpecSecretKeyRefName, ..} ) <$> f v1HelmReleaseSpecSecretKeyRefName
{-# INLINE v1HelmReleaseSpecSecretKeyRefNameL #-}

-- | 'v1HelmReleaseSpecSecretKeyRefNamespace' Lens
v1HelmReleaseSpecSecretKeyRefNamespaceL :: Lens_' V1HelmReleaseSpecSecretKeyRef (Maybe Text)
v1HelmReleaseSpecSecretKeyRefNamespaceL f V1HelmReleaseSpecSecretKeyRef{..} = (\v1HelmReleaseSpecSecretKeyRefNamespace -> V1HelmReleaseSpecSecretKeyRef { v1HelmReleaseSpecSecretKeyRefNamespace, ..} ) <$> f v1HelmReleaseSpecSecretKeyRefNamespace
{-# INLINE v1HelmReleaseSpecSecretKeyRefNamespaceL #-}

-- | 'v1HelmReleaseSpecSecretKeyRefOptional' Lens
v1HelmReleaseSpecSecretKeyRefOptionalL :: Lens_' V1HelmReleaseSpecSecretKeyRef (Maybe Bool)
v1HelmReleaseSpecSecretKeyRefOptionalL f V1HelmReleaseSpecSecretKeyRef{..} = (\v1HelmReleaseSpecSecretKeyRefOptional -> V1HelmReleaseSpecSecretKeyRef { v1HelmReleaseSpecSecretKeyRefOptional, ..} ) <$> f v1HelmReleaseSpecSecretKeyRefOptional
{-# INLINE v1HelmReleaseSpecSecretKeyRefOptionalL #-}



-- * V1HelmReleaseSpecTest

-- | 'v1HelmReleaseSpecTestCleanup' Lens
v1HelmReleaseSpecTestCleanupL :: Lens_' V1HelmReleaseSpecTest (Maybe Bool)
v1HelmReleaseSpecTestCleanupL f V1HelmReleaseSpecTest{..} = (\v1HelmReleaseSpecTestCleanup -> V1HelmReleaseSpecTest { v1HelmReleaseSpecTestCleanup, ..} ) <$> f v1HelmReleaseSpecTestCleanup
{-# INLINE v1HelmReleaseSpecTestCleanupL #-}

-- | 'v1HelmReleaseSpecTestEnable' Lens
v1HelmReleaseSpecTestEnableL :: Lens_' V1HelmReleaseSpecTest (Maybe Bool)
v1HelmReleaseSpecTestEnableL f V1HelmReleaseSpecTest{..} = (\v1HelmReleaseSpecTestEnable -> V1HelmReleaseSpecTest { v1HelmReleaseSpecTestEnable, ..} ) <$> f v1HelmReleaseSpecTestEnable
{-# INLINE v1HelmReleaseSpecTestEnableL #-}

-- | 'v1HelmReleaseSpecTestIgnoreFailures' Lens
v1HelmReleaseSpecTestIgnoreFailuresL :: Lens_' V1HelmReleaseSpecTest (Maybe Bool)
v1HelmReleaseSpecTestIgnoreFailuresL f V1HelmReleaseSpecTest{..} = (\v1HelmReleaseSpecTestIgnoreFailures -> V1HelmReleaseSpecTest { v1HelmReleaseSpecTestIgnoreFailures, ..} ) <$> f v1HelmReleaseSpecTestIgnoreFailures
{-# INLINE v1HelmReleaseSpecTestIgnoreFailuresL #-}

-- | 'v1HelmReleaseSpecTestTimeout' Lens
v1HelmReleaseSpecTestTimeoutL :: Lens_' V1HelmReleaseSpecTest (Maybe Integer)
v1HelmReleaseSpecTestTimeoutL f V1HelmReleaseSpecTest{..} = (\v1HelmReleaseSpecTestTimeout -> V1HelmReleaseSpecTest { v1HelmReleaseSpecTestTimeout, ..} ) <$> f v1HelmReleaseSpecTestTimeout
{-# INLINE v1HelmReleaseSpecTestTimeoutL #-}



-- * V1HelmReleaseSpecValueFileSecrets

-- | 'v1HelmReleaseSpecValueFileSecretsName' Lens
v1HelmReleaseSpecValueFileSecretsNameL :: Lens_' V1HelmReleaseSpecValueFileSecrets (Text)
v1HelmReleaseSpecValueFileSecretsNameL f V1HelmReleaseSpecValueFileSecrets{..} = (\v1HelmReleaseSpecValueFileSecretsName -> V1HelmReleaseSpecValueFileSecrets { v1HelmReleaseSpecValueFileSecretsName, ..} ) <$> f v1HelmReleaseSpecValueFileSecretsName
{-# INLINE v1HelmReleaseSpecValueFileSecretsNameL #-}



-- * V1HelmReleaseSpecValuesFrom

-- | 'v1HelmReleaseSpecValuesFromChartFileRef' Lens
v1HelmReleaseSpecValuesFromChartFileRefL :: Lens_' V1HelmReleaseSpecValuesFrom (Maybe V1HelmReleaseSpecChartFileRef)
v1HelmReleaseSpecValuesFromChartFileRefL f V1HelmReleaseSpecValuesFrom{..} = (\v1HelmReleaseSpecValuesFromChartFileRef -> V1HelmReleaseSpecValuesFrom { v1HelmReleaseSpecValuesFromChartFileRef, ..} ) <$> f v1HelmReleaseSpecValuesFromChartFileRef
{-# INLINE v1HelmReleaseSpecValuesFromChartFileRefL #-}

-- | 'v1HelmReleaseSpecValuesFromConfigMapKeyRef' Lens
v1HelmReleaseSpecValuesFromConfigMapKeyRefL :: Lens_' V1HelmReleaseSpecValuesFrom (Maybe V1HelmReleaseSpecConfigMapKeyRef)
v1HelmReleaseSpecValuesFromConfigMapKeyRefL f V1HelmReleaseSpecValuesFrom{..} = (\v1HelmReleaseSpecValuesFromConfigMapKeyRef -> V1HelmReleaseSpecValuesFrom { v1HelmReleaseSpecValuesFromConfigMapKeyRef, ..} ) <$> f v1HelmReleaseSpecValuesFromConfigMapKeyRef
{-# INLINE v1HelmReleaseSpecValuesFromConfigMapKeyRefL #-}

-- | 'v1HelmReleaseSpecValuesFromExternalSourceRef' Lens
v1HelmReleaseSpecValuesFromExternalSourceRefL :: Lens_' V1HelmReleaseSpecValuesFrom (Maybe V1HelmReleaseSpecExternalSourceRef)
v1HelmReleaseSpecValuesFromExternalSourceRefL f V1HelmReleaseSpecValuesFrom{..} = (\v1HelmReleaseSpecValuesFromExternalSourceRef -> V1HelmReleaseSpecValuesFrom { v1HelmReleaseSpecValuesFromExternalSourceRef, ..} ) <$> f v1HelmReleaseSpecValuesFromExternalSourceRef
{-# INLINE v1HelmReleaseSpecValuesFromExternalSourceRefL #-}

-- | 'v1HelmReleaseSpecValuesFromSecretKeyRef' Lens
v1HelmReleaseSpecValuesFromSecretKeyRefL :: Lens_' V1HelmReleaseSpecValuesFrom (Maybe V1HelmReleaseSpecSecretKeyRef)
v1HelmReleaseSpecValuesFromSecretKeyRefL f V1HelmReleaseSpecValuesFrom{..} = (\v1HelmReleaseSpecValuesFromSecretKeyRef -> V1HelmReleaseSpecValuesFrom { v1HelmReleaseSpecValuesFromSecretKeyRef, ..} ) <$> f v1HelmReleaseSpecValuesFromSecretKeyRef
{-# INLINE v1HelmReleaseSpecValuesFromSecretKeyRefL #-}



-- * V1HelmReleaseStatus

-- | 'v1HelmReleaseStatusConditions' Lens
v1HelmReleaseStatusConditionsL :: Lens_' V1HelmReleaseStatus (Maybe [V1HelmReleaseStatusConditions])
v1HelmReleaseStatusConditionsL f V1HelmReleaseStatus{..} = (\v1HelmReleaseStatusConditions -> V1HelmReleaseStatus { v1HelmReleaseStatusConditions, ..} ) <$> f v1HelmReleaseStatusConditions
{-# INLINE v1HelmReleaseStatusConditionsL #-}

-- | 'v1HelmReleaseStatusLastAttemptedRevision' Lens
v1HelmReleaseStatusLastAttemptedRevisionL :: Lens_' V1HelmReleaseStatus (Maybe Text)
v1HelmReleaseStatusLastAttemptedRevisionL f V1HelmReleaseStatus{..} = (\v1HelmReleaseStatusLastAttemptedRevision -> V1HelmReleaseStatus { v1HelmReleaseStatusLastAttemptedRevision, ..} ) <$> f v1HelmReleaseStatusLastAttemptedRevision
{-# INLINE v1HelmReleaseStatusLastAttemptedRevisionL #-}

-- | 'v1HelmReleaseStatusObservedGeneration' Lens
v1HelmReleaseStatusObservedGenerationL :: Lens_' V1HelmReleaseStatus (Maybe Integer)
v1HelmReleaseStatusObservedGenerationL f V1HelmReleaseStatus{..} = (\v1HelmReleaseStatusObservedGeneration -> V1HelmReleaseStatus { v1HelmReleaseStatusObservedGeneration, ..} ) <$> f v1HelmReleaseStatusObservedGeneration
{-# INLINE v1HelmReleaseStatusObservedGenerationL #-}

-- | 'v1HelmReleaseStatusPhase' Lens
v1HelmReleaseStatusPhaseL :: Lens_' V1HelmReleaseStatus (Maybe E'Phase)
v1HelmReleaseStatusPhaseL f V1HelmReleaseStatus{..} = (\v1HelmReleaseStatusPhase -> V1HelmReleaseStatus { v1HelmReleaseStatusPhase, ..} ) <$> f v1HelmReleaseStatusPhase
{-# INLINE v1HelmReleaseStatusPhaseL #-}

-- | 'v1HelmReleaseStatusReleaseName' Lens
v1HelmReleaseStatusReleaseNameL :: Lens_' V1HelmReleaseStatus (Maybe Text)
v1HelmReleaseStatusReleaseNameL f V1HelmReleaseStatus{..} = (\v1HelmReleaseStatusReleaseName -> V1HelmReleaseStatus { v1HelmReleaseStatusReleaseName, ..} ) <$> f v1HelmReleaseStatusReleaseName
{-# INLINE v1HelmReleaseStatusReleaseNameL #-}

-- | 'v1HelmReleaseStatusReleaseStatus' Lens
v1HelmReleaseStatusReleaseStatusL :: Lens_' V1HelmReleaseStatus (Maybe Text)
v1HelmReleaseStatusReleaseStatusL f V1HelmReleaseStatus{..} = (\v1HelmReleaseStatusReleaseStatus -> V1HelmReleaseStatus { v1HelmReleaseStatusReleaseStatus, ..} ) <$> f v1HelmReleaseStatusReleaseStatus
{-# INLINE v1HelmReleaseStatusReleaseStatusL #-}

-- | 'v1HelmReleaseStatusRevision' Lens
v1HelmReleaseStatusRevisionL :: Lens_' V1HelmReleaseStatus (Maybe Text)
v1HelmReleaseStatusRevisionL f V1HelmReleaseStatus{..} = (\v1HelmReleaseStatusRevision -> V1HelmReleaseStatus { v1HelmReleaseStatusRevision, ..} ) <$> f v1HelmReleaseStatusRevision
{-# INLINE v1HelmReleaseStatusRevisionL #-}

-- | 'v1HelmReleaseStatusRollbackCount' Lens
v1HelmReleaseStatusRollbackCountL :: Lens_' V1HelmReleaseStatus (Maybe Integer)
v1HelmReleaseStatusRollbackCountL f V1HelmReleaseStatus{..} = (\v1HelmReleaseStatusRollbackCount -> V1HelmReleaseStatus { v1HelmReleaseStatusRollbackCount, ..} ) <$> f v1HelmReleaseStatusRollbackCount
{-# INLINE v1HelmReleaseStatusRollbackCountL #-}



-- * V1HelmReleaseStatusConditions

-- | 'v1HelmReleaseStatusConditionsLastTransitionTime' Lens
v1HelmReleaseStatusConditionsLastTransitionTimeL :: Lens_' V1HelmReleaseStatusConditions (Maybe DateTime)
v1HelmReleaseStatusConditionsLastTransitionTimeL f V1HelmReleaseStatusConditions{..} = (\v1HelmReleaseStatusConditionsLastTransitionTime -> V1HelmReleaseStatusConditions { v1HelmReleaseStatusConditionsLastTransitionTime, ..} ) <$> f v1HelmReleaseStatusConditionsLastTransitionTime
{-# INLINE v1HelmReleaseStatusConditionsLastTransitionTimeL #-}

-- | 'v1HelmReleaseStatusConditionsLastUpdateTime' Lens
v1HelmReleaseStatusConditionsLastUpdateTimeL :: Lens_' V1HelmReleaseStatusConditions (Maybe DateTime)
v1HelmReleaseStatusConditionsLastUpdateTimeL f V1HelmReleaseStatusConditions{..} = (\v1HelmReleaseStatusConditionsLastUpdateTime -> V1HelmReleaseStatusConditions { v1HelmReleaseStatusConditionsLastUpdateTime, ..} ) <$> f v1HelmReleaseStatusConditionsLastUpdateTime
{-# INLINE v1HelmReleaseStatusConditionsLastUpdateTimeL #-}

-- | 'v1HelmReleaseStatusConditionsMessage' Lens
v1HelmReleaseStatusConditionsMessageL :: Lens_' V1HelmReleaseStatusConditions (Maybe Text)
v1HelmReleaseStatusConditionsMessageL f V1HelmReleaseStatusConditions{..} = (\v1HelmReleaseStatusConditionsMessage -> V1HelmReleaseStatusConditions { v1HelmReleaseStatusConditionsMessage, ..} ) <$> f v1HelmReleaseStatusConditionsMessage
{-# INLINE v1HelmReleaseStatusConditionsMessageL #-}

-- | 'v1HelmReleaseStatusConditionsReason' Lens
v1HelmReleaseStatusConditionsReasonL :: Lens_' V1HelmReleaseStatusConditions (Maybe Text)
v1HelmReleaseStatusConditionsReasonL f V1HelmReleaseStatusConditions{..} = (\v1HelmReleaseStatusConditionsReason -> V1HelmReleaseStatusConditions { v1HelmReleaseStatusConditionsReason, ..} ) <$> f v1HelmReleaseStatusConditionsReason
{-# INLINE v1HelmReleaseStatusConditionsReasonL #-}

-- | 'v1HelmReleaseStatusConditionsStatus' Lens
v1HelmReleaseStatusConditionsStatusL :: Lens_' V1HelmReleaseStatusConditions (E'Status)
v1HelmReleaseStatusConditionsStatusL f V1HelmReleaseStatusConditions{..} = (\v1HelmReleaseStatusConditionsStatus -> V1HelmReleaseStatusConditions { v1HelmReleaseStatusConditionsStatus, ..} ) <$> f v1HelmReleaseStatusConditionsStatus
{-# INLINE v1HelmReleaseStatusConditionsStatusL #-}

-- | 'v1HelmReleaseStatusConditionsType' Lens
v1HelmReleaseStatusConditionsTypeL :: Lens_' V1HelmReleaseStatusConditions (E'Type)
v1HelmReleaseStatusConditionsTypeL f V1HelmReleaseStatusConditions{..} = (\v1HelmReleaseStatusConditionsType -> V1HelmReleaseStatusConditions { v1HelmReleaseStatusConditionsType, ..} ) <$> f v1HelmReleaseStatusConditionsType
{-# INLINE v1HelmReleaseStatusConditionsTypeL #-}


